// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJAXlJNTnFRBotg4RnkDYcYRsz7xM5XEo',
    appId: '1:805368861395:web:3cb5466d1b97a0dd517a26',
    messagingSenderId: '805368861395',
    projectId: 'citaapp-19692',
    authDomain: 'citaapp-19692.firebaseapp.com',
    storageBucket: 'citaapp-19692.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwzTH9ibzMcl4jADRjPOP8sxYlCbgkjRk',
    appId: '1:805368861395:android:c40fab96f77e305d517a26',
    messagingSenderId: '805368861395',
    projectId: 'citaapp-19692',
    storageBucket: 'citaapp-19692.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9I3dCuonHlzKoM2ToEA-8PjFlAEIb510',
    appId: '1:805368861395:ios:7e049f0576848782517a26',
    messagingSenderId: '805368861395',
    projectId: 'citaapp-19692',
    storageBucket: 'citaapp-19692.firebasestorage.app',
    iosBundleId: 'com.example.appPruebas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9I3dCuonHlzKoM2ToEA-8PjFlAEIb510',
    appId: '1:805368861395:ios:7e049f0576848782517a26',
    messagingSenderId: '805368861395',
    projectId: 'citaapp-19692',
    storageBucket: 'citaapp-19692.firebasestorage.app',
    iosBundleId: 'com.example.appPruebas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJAXlJNTnFRBotg4RnkDYcYRsz7xM5XEo',
    appId: '1:805368861395:web:72d56551c929fcfb517a26',
    messagingSenderId: '805368861395',
    projectId: 'citaapp-19692',
    authDomain: 'citaapp-19692.firebaseapp.com',
    storageBucket: 'citaapp-19692.firebasestorage.app',
  );
}
